#!/bin/bash
if [ $(whoami) != "root" ]; then
        echo "This script must be run as root"
        exit 1
fi

/usr/loca/bin/jmap_hist_live_all || exit 1
/usr/local/bin/flush_cache || exit 1
/usr/local/bin/renice_all || exit 1

