#!/bin/bash

if [ $(whoami) != "root" ]; then
        echo "This script must be run as root"
        exit 1
fi

free -h
grep -e Dirty: -e Writeback: /proc/meminfo
sync
grep -e Dirty: -e Writeback: /proc/meminfo
echo 3 > /proc/sys/vm/drop_caches
free -h
