#!/bin/bash
if [ $(whoami) != "root" ]; then
        echo "This script must be run as root"
        exit 1
fi

## jmap -histo:live <pid>
## https://qiita.com/geishagirlskoume/items/ffa54eaa141c7892c88e#comment-7ddd420126ad93e7aa28
ps --no-heading -o user,pid -C java | while read user pid;
do
	sudo -u $user /bin/jmap -histo:live $pid
done

