#!/bin/bash

if [ $(whoami) != "root" ]; then
	echo "This script must be run as root"
	exit 1
fi

nice_value=19
if [ $@ > 0 ] ;then
	if expr "$1" : '[0-9]*' > /dev/null ; then
		nice_value=$1
	fi
fi
echo "changing nice value to ${nice_value}..."
## renice_all
ps --no-heading -eo user | sort | uniq | while read user
do
    renice -n ${nice_value} -u ${user}
done

